import { Submission } from "@/types";
import { generateSummary } from "@/lib/recommendations";

function makeSub(
  id: string,
  name: string,
  answers: Record<string, string | string[]>,
  status: "new" | "qualified" | "proposal_sent" | "closed",
  daysAgo: number
): Submission {
  const date = new Date();
  date.setDate(date.getDate() - daysAgo);
  date.setHours(9 + Math.floor(Math.random() * 8), Math.floor(Math.random() * 60));
  return {
    id,
    answers,
    summary: generateSummary(answers),
    status,
    createdAt: date.toISOString(),
    businessName: name,
  };
}

export const demoSubmissions: Submission[] = [
  makeSub(
    "demo-001",
    "Sunrise Bakery",
    {
      business_name: "Sunrise Bakery",
      business_description: "Artisan sourdough and pastries",
      brand_vibe: ["warm", "creative"],
      location: "Portland, OR",
      contact_email: "hello@sunrisebakery.com",
      contact_phone: "(503) 555-0142",
      social_media: ["https://instagram.com/sunrisebakerypdx"],
      operating_hours: "Tue-Sun 7am-3pm",
      primary_goals: ["customers", "showcase", "bookings"],
      visitor_action: "browse",
      has_photos: "professional",
      services_list: "- Sourdough loaves\n- Croissants & pastries\n- Custom cakes\n- Catering platters\n- Coffee & espresso",
      needs_reservations: "yes",
      reservation_details: "Pre-order pickup slots for bread and custom cakes",
      needs_ordering: "products",
      ordering_details: "Online ordering for bread subscriptions and pastry boxes",
      needs_events: "maybe",
      needs_contact_form: "yes",
      inspiration_links: ["https://tartinebakery.com", "https://flourbakerysf.com"],
      inspiration_why: "Love the warm photography and how the menu is presented. The ordering flow on Tartine is seamless.",
      wants_seo: "yes",
      plans_ads: "planning",
      wants_email_collection: "yes",
      expansion_plans: "Opening a second location in Lake Oswego next spring",
      new_services: "Launching a bread subscription box for home delivery",
      perfect_website: "A site that feels as warm as our bakery smells. Customers should be able to browse, pre-order, and sign up for our bread club.",
    },
    "qualified",
    2
  ),
  makeSub(
    "demo-002",
    "Apex Fitness Studio",
    {
      business_name: "Apex Fitness Studio",
      business_description: "High-intensity group fitness",
      brand_vibe: ["bold", "tech"],
      location: "Austin, TX",
      contact_email: "info@apexfit.co",
      contact_phone: "(512) 555-0289",
      social_media: ["https://instagram.com/apexfitstudio", "https://facebook.com/apexfit"],
      operating_hours: "Mon-Sat 5am-9pm, Sun 7am-5pm",
      primary_goals: ["customers", "bookings", "credibility"],
      visitor_action: "book",
      has_photos: "professional",
      services_list: "- HIIT classes\n- Strength training\n- Yoga\n- Personal training\n- Nutrition coaching",
      needs_reservations: "yes",
      reservation_details: "Class bookings with schedule calendar",
      needs_ordering: "services",
      ordering_details: "Membership sign-ups and personal training packages",
      needs_events: "yes",
      needs_contact_form: "yes",
      wants_seo: "yes",
      plans_ads: "already",
      wants_email_collection: "yes",
      new_services: "Launching an on-demand video library",
      perfect_website: "Something that feels energetic and modern. Easy class booking is the #1 priority.",
    },
    "proposal_sent",
    5
  ),
  makeSub(
    "demo-003",
    "Greenline Architecture",
    {
      business_name: "Greenline Architecture",
      business_description: "Sustainable residential design",
      brand_vibe: ["minimal", "luxurious", "professional"],
      location: "Denver, CO",
      contact_email: "studio@greenlinearch.com",
      primary_goals: ["showcase", "credibility", "customers"],
      visitor_action: "learn",
      has_photos: "professional",
      services_list: "- Custom home design\n- Renovation consulting\n- Sustainable building planning\n- 3D visualization",
      needs_reservations: "yes",
      reservation_details: "Free consultation bookings",
      needs_ordering: "services",
      ordering_details: "Project inquiry and quote requests",
      needs_events: "no",
      needs_contact_form: "yes",
      inspiration_links: ["https://olsonkundig.com", "https://feldmanarchitecture.com"],
      inspiration_why: "The portfolio presentation is stunning. Large imagery, minimal text, projects speak for themselves.",
      wants_seo: "yes",
      plans_ads: "maybe",
      wants_email_collection: "maybe",
      expansion_plans: "Expanding into commercial projects next year",
      perfect_website: "A portfolio that showcases our work beautifully. Clean, minimal, and premium feeling. Our projects should be the star.",
    },
    "new",
    0
  ),
  makeSub(
    "demo-004",
    "Little Sprouts Daycare",
    {
      business_name: "Little Sprouts Daycare",
      business_description: "Nurturing early childhood care",
      brand_vibe: ["warm", "fun"],
      location: "Nashville, TN",
      contact_email: "enroll@littlesprouts.com",
      contact_phone: "(615) 555-0371",
      social_media: ["https://facebook.com/littlesproutsnash"],
      operating_hours: "Mon-Fri 6:30am-6pm",
      primary_goals: ["customers", "credibility", "content"],
      visitor_action: "contact",
      has_photos: "phone",
      services_list: "- Infant care (6 weeks - 12 months)\n- Toddler program\n- Pre-K prep\n- After-school care\n- Summer camp",
      needs_reservations: "no",
      needs_ordering: "no",
      needs_events: "maybe",
      needs_contact_form: "yes",
      wants_seo: "yes",
      plans_ads: "planning",
      wants_email_collection: "yes",
      perfect_website: "Parents need to feel trust immediately. Testimonials, photos of the space, and easy enrollment info.",
    },
    "new",
    1
  ),
  makeSub(
    "demo-005",
    "Catalyst Marketing Co",
    {
      business_name: "Catalyst Marketing Co",
      business_description: "Data-driven digital marketing",
      brand_vibe: ["tech", "professional", "bold"],
      location: "Online only",
      contact_email: "hello@catalystmktg.com",
      social_media: ["https://linkedin.com/company/catalyst-marketing"],
      primary_goals: ["customers", "showcase", "credibility"],
      visitor_action: "contact",
      has_photos: "some",
      services_list: "- SEO & content strategy\n- PPC management\n- Social media marketing\n- Analytics & reporting\n- Brand consulting",
      needs_reservations: "yes",
      reservation_details: "Discovery call booking",
      needs_ordering: "services",
      ordering_details: "Monthly retainer packages",
      needs_events: "no",
      needs_contact_form: "yes",
      inspiration_links: ["https://webflow.com", "https://linear.app"],
      inspiration_why: "The clean design and how they communicate complex services simply. Great use of whitespace.",
      wants_seo: "yes",
      plans_ads: "already",
      wants_email_collection: "yes",
      new_services: "Launching an AI-powered audit tool",
      perfect_website: "We help other businesses with marketing — our own site needs to be flawless. Case studies and results front and center.",
    },
    "closed",
    14
  ),
];
