import { Question } from "@/types";

export const questions: Question[] = [
  // A. Brand Identity
  {
    id: "business_name",
    section: "brand",
    sectionLabel: "Brand Identity",
    question: "What's the name of your business?",
    subtitle: "This helps us personalize your experience.",
    type: "text",
    placeholder: "e.g. Sunrise Bakery",
    required: true,
  },
  {
    id: "business_description",
    section: "brand",
    sectionLabel: "Brand Identity",
    question: "Describe your business in 3–5 words.",
    subtitle: "Think of it as your elevator pitch in miniature.",
    type: "text",
    placeholder: "e.g. Modern artisan coffee roasters",
    required: true,
  },
  {
    id: "brand_vibe",
    section: "brand",
    sectionLabel: "Brand Identity",
    question: "What vibe best fits your brand?",
    subtitle: "Pick all that resonate with you.",
    type: "multiselect",
    options: [
      { label: "Professional & Corporate", value: "professional" },
      { label: "Creative & Artistic", value: "creative" },
      { label: "Warm & Friendly", value: "warm" },
      { label: "Bold & Edgy", value: "bold" },
      { label: "Luxurious & Premium", value: "luxurious" },
      { label: "Minimal & Clean", value: "minimal" },
      { label: "Fun & Playful", value: "fun" },
      { label: "Tech & Modern", value: "tech" },
    ],
    required: true,
  },
  {
    id: "logo_upload",
    section: "brand",
    sectionLabel: "Brand Identity",
    question: "Have a logo? Upload it here.",
    subtitle: "Don't worry if you don't have one yet — we can help with that.",
    type: "file",
    required: false,
  },

  // B. Business Details
  {
    id: "location",
    section: "business",
    sectionLabel: "Business Details",
    question: "Where is your business located?",
    subtitle: "City, state, or 'Online only' if you're fully remote.",
    type: "text",
    placeholder: "e.g. Austin, TX",
    required: true,
  },
  {
    id: "contact_email",
    section: "business",
    sectionLabel: "Business Details",
    question: "What's the best email to reach you?",
    type: "email",
    placeholder: "you@business.com",
    required: true,
  },
  {
    id: "contact_phone",
    section: "business",
    sectionLabel: "Business Details",
    question: "What's your phone number?",
    subtitle: "We'll only use this if we need to follow up.",
    type: "phone",
    placeholder: "(555) 123-4567",
    required: false,
  },
  {
    id: "social_media",
    section: "business",
    sectionLabel: "Business Details",
    question: "Drop your social media links.",
    subtitle: "Instagram, Facebook, LinkedIn — whatever you've got.",
    type: "links",
    placeholder: "https://instagram.com/yourbusiness",
    required: false,
  },
  {
    id: "operating_hours",
    section: "business",
    sectionLabel: "Business Details",
    question: "What are your operating hours?",
    subtitle: "If applicable — skip this if you're online only.",
    type: "text",
    placeholder: "e.g. Mon–Fri 9am–5pm",
    required: false,
  },

  // C. Website Goals
  {
    id: "primary_goals",
    section: "goals",
    sectionLabel: "Website Goals",
    question: "What's the #1 thing you want your website to do?",
    subtitle: "Select all that apply.",
    type: "multiselect",
    options: [
      { label: "Get more customers", value: "customers" },
      { label: "Showcase services or products", value: "showcase" },
      { label: "Accept bookings or appointments", value: "bookings" },
      { label: "Build credibility & trust", value: "credibility" },
      { label: "Sell products online", value: "ecommerce" },
      { label: "Share information & content", value: "content" },
    ],
    required: true,
  },
  {
    id: "visitor_action",
    section: "goals",
    sectionLabel: "Website Goals",
    question: "When someone visits your site, what should they do first?",
    subtitle: "Think about the single most important action.",
    type: "select",
    options: [
      { label: "Call or contact you", value: "contact" },
      { label: "Book an appointment", value: "book" },
      { label: "Browse your menu/services", value: "browse" },
      { label: "Make a purchase", value: "purchase" },
      { label: "Learn about your business", value: "learn" },
      { label: "Sign up for updates", value: "signup" },
    ],
    required: true,
  },

  // D. Content & Assets
  {
    id: "has_photos",
    section: "content",
    sectionLabel: "Content & Assets",
    question: "Do you already have photos or videos of your business?",
    subtitle: "Professional shots, phone photos — anything works.",
    type: "select",
    options: [
      { label: "Yes, professional photos", value: "professional" },
      { label: "Yes, but just phone photos", value: "phone" },
      { label: "A few, but need more", value: "some" },
      { label: "No, I need help with this", value: "none" },
    ],
    required: true,
  },
  {
    id: "content_upload",
    section: "content",
    sectionLabel: "Content & Assets",
    question: "Want to upload any files now?",
    subtitle: "Photos, menus, brochures, brand guides — drop them here.",
    type: "file",
    required: false,
  },
  {
    id: "services_list",
    section: "content",
    sectionLabel: "Content & Assets",
    question: "List your main services or products.",
    subtitle: "A quick list is fine — we'll help organize it later.",
    type: "textarea",
    placeholder: "e.g.\n- Web Design\n- Logo Design\n- SEO Optimization",
    required: false,
  },

  // E. Features Needed
  {
    id: "needs_reservations",
    section: "features",
    sectionLabel: "Features Needed",
    question: "Do you need an online reservation or booking system?",
    type: "select",
    options: [
      { label: "Yes, definitely", value: "yes" },
      { label: "Maybe — tell me more", value: "maybe" },
      { label: "No, not needed", value: "no" },
    ],
    required: true,
  },
  {
    id: "reservation_details",
    section: "features",
    sectionLabel: "Features Needed",
    question: "What kind of bookings would you take?",
    subtitle: "Help us understand so we can recommend the right setup.",
    type: "text",
    placeholder: "e.g. Table reservations, consultations, classes",
    condition: { questionId: "needs_reservations", value: ["yes", "maybe"] },
    required: false,
  },
  {
    id: "needs_ordering",
    section: "features",
    sectionLabel: "Features Needed",
    question: "Will customers need to purchase, order, or request anything through your site?",
    subtitle: "This includes physical products, services, quotes, or project inquiries.",
    type: "select",
    options: [
      { label: "Yes — sell products online", value: "products" },
      { label: "Yes — accept service requests or quote inquiries", value: "services" },
      { label: "Yes — both products and services", value: "both" },
      { label: "Maybe in the future", value: "maybe" },
      { label: "No, not needed", value: "no" },
    ],
    required: true,
  },
  {
    id: "ordering_details",
    section: "features",
    sectionLabel: "Features Needed",
    question: "Tell us more about what you'd offer online.",
    subtitle: "This helps us recommend the right setup for your business type.",
    type: "text",
    placeholder: "e.g. Custom home builds, landscaping quotes, food delivery, clothing, gift cards",
    condition: { questionId: "needs_ordering", value: ["products", "services", "both", "maybe"] },
    required: false,
  },
  {
    id: "needs_events",
    section: "features",
    sectionLabel: "Features Needed",
    question: "Do you host events that need a calendar?",
    type: "select",
    options: [
      { label: "Yes", value: "yes" },
      { label: "Occasionally", value: "maybe" },
      { label: "No", value: "no" },
    ],
    required: true,
  },
  {
    id: "needs_contact_form",
    section: "features",
    sectionLabel: "Features Needed",
    question: "Do you want a contact form on your website?",
    type: "select",
    options: [
      { label: "Yes, essential", value: "yes" },
      { label: "Nice to have", value: "maybe" },
      { label: "No, not needed", value: "no" },
    ],
    required: true,
  },

  // F. Inspiration
  {
    id: "inspiration_links",
    section: "inspiration",
    sectionLabel: "Inspiration",
    question: "Share some websites you love.",
    subtitle: "They don't have to be in your industry — we just want to understand your taste.",
    type: "links",
    placeholder: "https://example.com",
    required: false,
  },
  {
    id: "inspiration_why",
    section: "inspiration",
    sectionLabel: "Inspiration",
    question: "What do you like about those websites?",
    subtitle: "The layout? Colors? How it feels? Tell us anything.",
    type: "textarea",
    placeholder: "e.g. I love how clean and easy to navigate it is...",
    required: false,
  },

  // G. Growth & Marketing
  {
    id: "wants_seo",
    section: "growth",
    sectionLabel: "Growth & Marketing",
    question: "Do you want your website optimized for Google search (SEO)?",
    subtitle: "This helps people find you when they search for businesses like yours.",
    type: "select",
    options: [
      { label: "Yes, very important", value: "yes" },
      { label: "Somewhat important", value: "somewhat" },
      { label: "Not a priority right now", value: "no" },
    ],
    required: true,
  },
  {
    id: "plans_ads",
    section: "growth",
    sectionLabel: "Growth & Marketing",
    question: "Are you planning to run online ads?",
    subtitle: "Google Ads, Facebook Ads, Instagram Ads, etc.",
    type: "select",
    options: [
      { label: "Yes, already running them", value: "already" },
      { label: "Planning to start", value: "planning" },
      { label: "Maybe in the future", value: "maybe" },
      { label: "No plans for ads", value: "no" },
    ],
    required: true,
  },
  {
    id: "wants_email_collection",
    section: "growth",
    sectionLabel: "Growth & Marketing",
    question: "Do you want to collect email addresses from visitors?",
    subtitle: "Great for newsletters, promotions, and staying in touch.",
    type: "select",
    options: [
      { label: "Yes, definitely", value: "yes" },
      { label: "Maybe later", value: "maybe" },
      { label: "No", value: "no" },
    ],
    required: true,
  },

  // H. Future Plans
  {
    id: "expansion_plans",
    section: "future",
    sectionLabel: "Future Plans",
    question: "Any expansion plans on the horizon?",
    subtitle: "New locations, markets, or big changes coming up?",
    type: "textarea",
    placeholder: "e.g. Opening a second location next year...",
    required: false,
  },
  {
    id: "new_services",
    section: "future",
    sectionLabel: "Future Plans",
    question: "Any new services or products you're launching?",
    subtitle: "We can plan the website to accommodate these from day one.",
    type: "textarea",
    placeholder: "e.g. Adding a catering service, launching merchandise...",
    required: false,
  },

  // I. Final Question
  {
    id: "perfect_website",
    section: "final",
    sectionLabel: "One Last Thing",
    question: "What would make this website absolutely perfect for you?",
    subtitle: "Dream big — we want to get this right.",
    type: "textarea",
    placeholder: "Tell us your vision...",
    required: false,
  },
];

export const sections = [
  { id: "brand", label: "Brand Identity", icon: "✦" },
  { id: "business", label: "Business Details", icon: "◆" },
  { id: "goals", label: "Website Goals", icon: "◎" },
  { id: "content", label: "Content & Assets", icon: "□" },
  { id: "features", label: "Features Needed", icon: "⚙" },
  { id: "inspiration", label: "Inspiration", icon: "★" },
  { id: "growth", label: "Growth & Marketing", icon: "↗" },
  { id: "future", label: "Future Plans", icon: "→" },
  { id: "final", label: "One Last Thing", icon: "♡" },
];
